# Website name
title: JV's Basketball Blog

# Short Tagline
tagline: Stats and analysis for the SEC and college basketball

# Website description
description: >-
  Jacob Varner's take on the SEC and college basketball including advanced stats
  analysis, SEC power rankings, a college basketball top 25, and SEC previews,
  game picks, and season predictions.

logo: /images/logo-black-on-white.png

# Author for Twitter summary card
author:
  twitter: jacobvarner

twitter:
  username: jacobvarner

facebook:
  publisher: 103514855024108

social:
  name: Jacob Varner
  links:
    - https://www.twitter.com/jacobvarner
    - https://www.facebook.com/hoops.jacobvarner

# Set default image and other fallbacks
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/logo-black-on-white.png
        height: 400
        width: 400

baseurl: "/"
url: "https://hoops.jacobvarner.com"

collections:
  mytags:
    output: true
    permalink: /tag/:name/

# Number of posts per page and url/slug used for pagination
paginate: 10
paginate_path: "/page:num/"

# Sets the Sass output style (nested, expanded, compact, compressed)
sass:
  style: compressed

# Include ads?
show_ads: true

# Set whether future dated posts are included or not
future: false

# Set timezone for site generation
timezone: America/Chicago

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
