# Website name
title: Jacob Varner's Basketball Blog

# Website description
description: >-
  Jacob Varner's personal blog for all things basketball with a focus on stats
  and analysis for Auburn and the SEC.

# Author for Twitter summary card
author:
  twitter: jacobvarner

# Set default image and other fallbacks
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/logo-black-on-white.png
        height: 400
        width: 400

baseurl: "/"
url: "https://hoops.jacobvarner.com"

# Number of posts per page and url/slug used for pagination
paginate: 10
paginate_path: "/page:num/"

# Sets the Sass output style (nested, expanded, compact, compressed)
sass:
  style: compressed

# Include ads?
show_ads: true

# Set whether future dated posts are included or not
future: false

# Set timezone for site generation
timezone: America/Chicago

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
